baltaIOCrud/Models/Purchase.cs
namespace baltaIOCrud.Models
{
    public class Purchase
    {
        public Guid Id { get; set; }
        public string CustomerId { get; set; }
        public Guid ProductId { get; set; }//talvez tenha dado problema aqui mas nao consegui fazer migration
        public string ProductName { get; set; }
        public int Quantity { get; set; }
        public decimal Price { get; set; }


    }
}

baltaIOCrud/Controllers/CartController.cs
using baltaIOCrud.Data;
using baltaIOCrud.Models;
using baltaIOCrud.Models.ViewModel;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.CodeAnalysis;
using Microsoft.EntityFrameworkCore;

namespace baltaIOCrud.Controllers
{
    public class CartController : Controller
    {
        public readonly ApplicationDbContext _context;
        //get the user id
        public readonly UserManager<IdentityUser> _userManager;
        public CartController(ApplicationDbContext context, UserManager<IdentityUser> userManager)
        {
            this._context = context;
            this._userManager = userManager;
        }
        [HttpGet]
        public async Task<IActionResult> DisplayItems(Guid Id)
        {
            var product = await _context.Products.FindAsync(Id);

            if (product == null)
            {
                // Product not found, handle the error
                return NotFound();
            }

            var viewModel = new CartViewModel
            {
                Id = Id,
                Items = new List<Products> // Initialize the Items property
                {
                    product // Add the retrieved product to the Items list
                },
                TotalQuantity = product.StockQuantity, // Set the total quantity
                TotalPrice = product.Price // Set the total price
                                           // Add other properties to the view model as needed
            };

            return View(viewModel);
        }
        //[HttpPost]
        //public async Task<IActionResult> AddToCart(Guid productId)
        //{
        //    var product = await _context.Products.FindAsync(productId);

        //    if (product == null)
        //    {
        //        // Product not found, handle the error
        //        return NotFound();
        //    }

        //    // Retrieve the current user ID or any other identifier for associating the cart items with the user
           
        //    // Check if the product already exists in the cart for the user
        //    var existingCartItem = await _context.Carts.FirstOrDefaultAsync(c => c.ProductId == productId && c.UserId == userId);

        //    if (existingCartItem != null)
        //    {
        //        // Product already exists in the cart, you can update the quantity or handle it as needed
        //        existingCartItem.Quantity += 1;
        //    }
        //    else
        //    {
        //        // Product does not exist in the cart, create a new cart item
        //        var cartItem = new Cart
        //        {
        //            Items = product.Id,
        //            Quantity = 1,
        //            UserId = userId
        //        };

        //        // Add the cart item to the Cart table
        //        _context.Cart.Add(cartItem);
        //    }

        //    await _context.SaveChangesAsync();

        //    // Optionally, you can provide feedback or redirect the user to the cart page after adding the product

        //    return RedirectToAction("Cart"); // Redirect to the cart page
        //}

        public IActionResult AddToCart(Products product)
        {
            return RedirectToAction();
        }
        public IActionResult RemoveToCart(Guid Id)
        {
            return RedirectToAction();
        }


    }
}

baltaIOCrud/Controllers/PurchaseController.cs
using baltaIOCrud.Data;
using baltaIOCrud.Models;
using baltaIOCrud.Models.ViewModel;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace baltaIOCrud.Controllers
{
    public class PurchaseController : Controller
    {
        //get the context
        public readonly ApplicationDbContext _context;
        //get the user id
        public readonly UserManager<IdentityUser> _userManager;

        public PurchaseController(ApplicationDbContext context, UserManager<IdentityUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        public async Task<IActionResult> Index()
        {
            var user = await _userManager.GetUserAsync(User);
            if (user == null) 
            {
                return NotFound();
            }
            var userId = user.Id;
            ViewBag.UserId = userId;

            var products = _context.Products.Where(p => p.StockQuantity > 0).ToList();
            var viewModel = new ProductViewModel { Products = products };

            return View(viewModel);
        }

        public async Task CreatePurchase(string userId, Guid productId, string productName, int quantity, decimal price)
        {
            var purchase = new Purchase
            {
                Id = Guid.NewGuid(),
                CustomerId = userId,
                ProductId = productId,
                ProductName = productName,
                Quantity = quantity,
                Price = price
            };
            _context.Purchases.Add(purchase);
            await _context.SaveChangesAsync();
        }

        [HttpGet]
        public async Task<IActionResult> Buy(Guid productId)
        {
            var user = await _userManager.GetUserAsync(User);
            var userId = user.Id;
            ViewBag.UserId = userId;

            var product = await _context.Products.FindAsync(productId);

            if (product == null)
            {
                // Product not found, handle the error
                return NotFound();
            }

            var viewModel = new UpdateStockQuantity
            {
                Id = productId,//get product id to update correctly
                StockQuantity = product.StockQuantity
            };

            return View(viewModel);
        }

        [HttpPost]
        public async Task<IActionResult> Buy(UpdateStockQuantity model, Guid Id)
        {
            var user = await _userManager.GetUserAsync(User);
            var userId = user.Id;
            if (!ModelState.IsValid)
            {
                return RedirectToAction("Index");
            }
            var product = await _context.Products.FindAsync(Id);
            if (product != null)
            {
                if (model.StockQuantity > product.StockQuantity)
                {
                    ModelState.AddModelError("StockQuantity", "Invalid stock quantity");
                    return View(model);
                }
                product.StockQuantity -= model.StockQuantity;
                if (product.StockQuantity == 0) 
                {
                    product.Available = false;
                   
                }
                _context.Update(product);
                await _context.SaveChangesAsync();
                await CreatePurchase(userId, product.Id, product.Name, model.StockQuantity, product.Price);
                return RedirectToAction("Index");
            }
            return RedirectToAction("Index");
        }
    }
}

baltaIOCrud/Views/Purchase/Buy.cshtml
@model baltaIOCrud.Models.ViewModel.UpdateStockQuantity

<h1>Edit Product</h1>

<form asp-action="Buy" method="post">
	<input type="text" asp-for="Id" />

	<div class="form-group">
		<label asp-for="StockQuantity">Stock Quantity</label>
		<input asp-for="StockQuantity" class="form-control" />
		<span asp-validation-for="StockQuantity" class="text-danger"></span>
		

	</div>

	<button type="submit" class="btn btn-primary">Save</button>
</form>

@*
<form method="post" action="@Url.Action("Buy", "Purchase")">
	@Html.AntiForgeryToken()
	<input type="text" asp-for="Id" />
	<div class="form-group">
		<label for="StockQuantity">Stock Quantity:</label>
		<input type="number" id="StockQuantity" name="StockQuantity" class="form-control" />
		@Html.ValidationMessageFor(model => model.StockQuantity)
	</div>

	<button type="submit" class="btn btn-primary">Buy</button>
</form>*@

baltaIOCrud/Views/Purchase/DetailProduct.cshtml
@model baltaIOCrud.Models.Products

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>SalesLeadEntity</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>

       
    </dl>
</div>
<div>

    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

baltaIOCrud/Views/Purchase/Index.cshtml
@model baltaIOCrud.Models.ProductViewModel
@*<h1>

    @ViewBag.UserId

</h1>*@
<h1>Available Products</h1>

@foreach (var product in Model.Products)
{
    <div>
        <h3>@product.Name</h3>
        <p>Price: @product.Price</p>
        <p>Quantity: @product.StockQuantity</p>
        <p>@product.Available</p>
        @*<button onclick="location.href='@Url.Action("Buy", "Purchase", new { productId = product.Id })'">Buy</button>*@
        <td><a asp-action="Buy" asp-controller="Purchase" asp-route-productId="@product.Id" class="btn btn-primary">Buy</a></td>
        <td><a asp-action="DisplayItems" asp-controller="Cart" asp-route-Id="@product.Id" class="btn btn-secondary">Add To Cart</a></td>
    </div>
}